In [1]:
import numpy as np
import em_algorithm
from simulation_framework.simulate_competency import respondent_population
from simulation_framework.simulate_responses import response_simulation
from scipy.stats import multivariate_normal
import models
import em_algorithm
import pandas as pd
import time

C:\Users\Jesper\Documents\GitHub\Knowledge-Growth-Prediction\models


In [2]:
def rmse(y_pred: np.array, y_true: np.array) -> float:
    MSE = np.square(np.subtract(y_pred.flatten(), y_true.flatten())).mean()
    RMSE = np.sqrt(MSE)
    return(float(RMSE))

def experiment_performance(estimated_parameter_dict, real_parameter_dict):
    A_pred = estimated_parameter_dict["item_parameters"]["discrimination_matrix"]
    delta_pred = estimated_parameter_dict["item_parameters"]["intercept_vector"]
    sigma_pred = estimated_parameter_dict["person_parameters"]["covariance"]

    A_true = real_parameter_dict["item_parameters"]["discrimination_matrix"]
    delta_true = real_parameter_dict["item_parameters"]["intercept_vector"]
    sigma_true = real_parameter_dict["person_parameters"]["covariance"]

    print("Absolute diff in A:")
    print(np.abs(A_true-A_pred))

    print("Absolute diff in delta:")
    print(np.abs(delta_true-delta_pred))

    print("Absolute diff in sigma:")
    print(np.abs(sigma_true-sigma_pred))    

    rmse_A = rmse(A_pred, A_true)
    rmse_delta = rmse(delta_true, delta_pred)
    rmse_sigma = rmse(sigma_true, sigma_pred) 

    return({"rmse_A": rmse_A, "rmse_delta": rmse_delta, "rmse_sigma": rmse_sigma})

## Experiment 0: MIRT-2PL Performance Benchmark

In [3]:
def mirt_performance_benchmark() -> dict:
    latent_dimension = 2
    item_dimension = 6
    sample_size=30

    #Define Population
    real_latent_cov = np.array([[1,0.2],
                    [0.2,1]])

    latent_distribution = multivariate_normal(mean=np.array([0,0]), cov=real_latent_cov)
    population = respondent_population(latent_dimension=latent_dimension, latent_distribution=latent_distribution)

    #Define Test
    A = np.array([[0.5,0],
                  [2,0],
                  [0,0.4],
                  [0.7,0.6],
                  [2, 0.9],
                  [0, 1.5]])
    Q = np.array([[1,0],
                  [1,0],
                  [0,1],
                  [1,1],
                  [1,1],
                  [0,1]])

    delta = np.array([0, 0.5, 1, 0, 1.5, 0.9])
    early_item_parameters = {"discrimination_matrix": A, "intercept_vector": delta, "q_matrix": Q, "item_dimension": item_dimension, "latent_dimension": latent_dimension}

    #Sample responses
    response_simulation_obj = response_simulation(population=population, early_item_params=early_item_parameters)
    sample = response_simulation_obj.sample(100)

    #Fit Parameters
    #Initialize model
    model = models.mirt_2pl(latent_dimension=2, item_dimension=6, A=Q, Q=Q, delta=np.ones(6), sigma=np.identity(2))
    e_step = em_algorithm.e_step_ga_mml(model=model)
    m_step = em_algorithm.m_step_ga_mml(model)
    em = em_algorithm.em_algo(e_step=e_step, m_step=m_step, model=model)

    #Fit Model
    start_time = time.time()
    em.fit(sample["early_responses"], max_iter=100)
    run_time =  (time.time() - start_time)

    #Measure Performance
    early_estimated_item_parameters = em.model.item_parameters
    early_estimated_person_parameters = em.model.person_parameters

    result_dict = {"sample": sample,
                   "real_early_parameters": {"item_parameters": early_item_parameters, "person_parameters": {"covariance": real_latent_cov}},
                   "estimated_early_parameters": {"item_parameters": early_estimated_item_parameters, "person_parameters": early_estimated_person_parameters},
                   "runtime": run_time,
                   "number_steps": em.n_steps}

    result_dict["early_performance"] = experiment_performance(estimated_parameter_dict=result_dict["real_early_parameters"], 
                                                              real_parameter_dict=result_dict["estimated_early_parameters"])


    return(result_dict)

In [4]:

def print_result(result_dict, description=""):
    print("------------------------------------")
    print("##### Results for {0}".format(description))
    print("Runtime: {0} seconds, {1} steps, {2} seconds per step \\".format(np.round(result_dict["runtime"], 2), np.round(result_dict["number_steps"], 2), 
    np.round(result_dict["runtime"]/result_dict["number_steps"], 2)))
    print("Performance: rmse-mean = {0}".format(np.round(np.mean(np.array(list(result_dict["early_performance"].values()))), 4)))

In [5]:
performance_dict = mirt_performance_benchmark()
#One Iteration: Runtime: 291 secs. 

EM Iteration 1
E-step
M-step
Maximize Q-0
Maximize the Q_i's
Step: 1: current parameter_diff: 6.576480367318885, current marginal loglikelihood: -413.286438424756
EM Iteration 2
E-step
M-step
Maximize Q-0
Maximize the Q_i's
Step: 2: current parameter_diff: 2.550534329939197, current marginal loglikelihood: -433.89249651345943
EM Iteration 3
E-step
M-step
Maximize Q-0
Maximize the Q_i's
Step: 3: current parameter_diff: 2.467016136466305, current marginal loglikelihood: -431.0422042246537
EM Iteration 4
E-step
M-step
Maximize Q-0


c:\Users\Jesper\Documents\GitHub\Knowledge-Growth-Prediction\em_algorithm\e_step_mirt_2pl.py:89: RuntimeWarning: divide by zero encountered in log
  factor = np.log(self.model.latent_density(theta, sigma=sigma))


Maximize the Q_i's
Step: 4: current parameter_diff: 0.3048380063739312, current marginal loglikelihood: -426.41685223338646
EM Iteration 5
E-step
M-step
Maximize Q-0
Maximize the Q_i's
Step: 5: current parameter_diff: 0.4954919288965167, current marginal loglikelihood: -423.26613189081684
EM Iteration 6
E-step
M-step
Maximize Q-0
Maximize the Q_i's
Step: 6: current parameter_diff: 0.5889558188530428, current marginal loglikelihood: -421.7043770745032
EM Iteration 7
E-step
M-step
Maximize Q-0
Maximize the Q_i's
Step: 7: current parameter_diff: 0.28421582357619335, current marginal loglikelihood: -422.19537346565454
EM Iteration 8
E-step
M-step
Maximize Q-0
Maximize the Q_i's
Step: 8: current parameter_diff: 0.06476566135614802, current marginal loglikelihood: -422.11490576329686
Absolute diff in A:
[[0.40244629 0.        ]
 [1.86729224 0.        ]
 [0.         0.33553226]
 [0.66697355 0.54633763]
 [1.96645873 0.57251536]
 [0.         1.34649414]]
Absolute diff in delta:
[1.11690177 0.55

In [6]:
print_result(performance_dict, "Add vectorization in Q_0")

------------------------------------
##### Results for Add vectorization in Q_0
Runtime: 20.23 seconds, 9 steps, 2.25 seconds per step \
Performance: rmse-mean = 0.6728


------------------------------------
##### Results for Naive, all-Genetic, no vectorization
Runtime: 29100 seconds, 100+ steps, 291 seconds per step\
Performance: rmse-mean = 0.5896464054719196

------------------------------------
##### Results for Vectorized q_item
Runtime: 613.3871161937714 seconds, 100+ steps, 6.0731397642947655 seconds per step \
Performance: rmse-mean = 0.6466789259215839

------------------------------------
##### Results for More precise results through higher N and pop_size
Runtime: 2239.073846578598 seconds, 100+ steps, 22.169047985926714 seconds per step \
Performance: rmse-mean = 0.6384660709857508

------------------------------------
##### Results for Debug GA sorting, Add Likelihood-based stopping criterion
Runtime: 135.11203932762146 seconds, 7 steps, 19.301719903945923 seconds per step \
Performance: rmse-mean = 0.5616448369465917

------------------------------------
##### Results for Add vectorization in Q_0
Runtime: 228.78 seconds, 17 steps, 13.46 seconds per step \
Performance: rmse-mean = 0.6174

## Procedure

1. Add Performance Benchmark (done)
2. Add Vectorization to q_item (done)
3. Add better Initialization
3. Add Vectorization to q_0 (done)
4. Add q_0 Derivation 1. + BFGS
5. Add q_0 Derivation 2. + Newton Raphson
6. Use cython

## Experiment 1: MIRT-2PL Parameter Recovery

In [16]:
from unittest import result


def mirt_param_recovery(sample_size) -> dict:
    latent_dimension = 2
    item_dimension = 6
    sample_size=30

    #Define Population
    real_latent_cov = np.array([[1,0.2],
                    [0.2,1]])

    latent_distribution = multivariate_normal(mean=np.array([0,0]), cov=real_latent_cov)
    population = respondent_population(latent_dimension=latent_dimension, latent_distribution=latent_distribution)

    #Define Test
    A = np.array([[0.5,0],
                  [2,0],
                  [0,0.4],
                  [0.7,0.6],
                  [2, 0.9],
                  [0, 1.5]])
    Q = np.array([[1,0],
                  [1,0],
                  [0,1],
                  [1,1],
                  [1,1],
                  [0,1]])

    delta = np.array([0, 0.5, 1, 0, 1.5, 0.9])
    early_item_parameters = {"discrimination_matrix": A, "intercept_vector": delta, "q_matrix": Q, "item_dimension": item_dimension, "latent_dimension": latent_dimension}

    #Sample responses
    response_simulation_obj = response_simulation(population=population, early_item_params=early_item_parameters)
    sample = response_simulation_obj.sample(100)

    #Fit Parameters
    #Initialize model
    model = models.mirt_2pl(latent_dimension=2, item_dimension=6, A=Q, Q=Q, delta=np.ones(6), sigma=np.identity(2))
    e_step = em_algorithm.e_step_ga_mml(model=model)
    m_step = em_algorithm.m_step_ga_mml(model)
    em = em_algorithm.em_algo(e_step=e_step, m_step=m_step, model=model)

    #Fit Model
    start_time = time.time()
    em.fit(sample["early_responses"], max_iter=100)
    run_time =  (time.time() - start_time)

    #Measure Performance
    early_estimated_item_parameters = em.model.item_parameters
    early_estimated_person_parameters = em.model.person_parameters

    result_dict = {"sample": sample,
                   "real_early_parameters": {"item_parameters": early_item_parameters, "person_parameters": {"covariance": real_latent_cov}},
                   "estimated_early_parameters": {"item_parameters": early_estimated_item_parameters, "person_parameters": early_estimated_person_parameters},
                   "runtime": run_time,
                   "number_steps": em.n_steps}

    result_dict["early_performance"] = experiment_performance(estimated_parameter_dict=result_dict["real_early_parameters"], 
                                                              real_parameter_dict=result_dict["estimated_early_parameters"])


    return(result_dict)

In [3]:


#sample data
exper_dict = mirt_param_recovery(30)
U = exper_dict["sample"]["early_responses"]
Q = exper_dict["early_item_parameters"]["q_matrix"]

#Initialize model
model = models.mirt_2pl(latent_dimension=2, item_dimension=6, A=Q, Q=Q, delta=np.ones(6), sigma=np.identity(2))

e_step = em_algorithm.e_step_ga_mml(incomplete_data=U, model=model)
m_step = em_algorithm.m_step_ga_mml(model)

em = em_algorithm.em_algo(e_step=e_step, m_step=m_step, model=model)
em.fit(U, max_iter=5)


EM Iteration 1
E-step
M-step
Maximize Q-0
Highest Current Fitness:
-272.3020964947444
Length of Population = 20
Highest Current Fitness:
-272.3020964947444
Length of Population = 30
Maximize the Q_i's
Highest Current Fitness:
-80.38694365262204
Length of Population = 20
Highest Current Fitness:
-81.64548958485268
Length of Population = 20
Highest Current Fitness:
-70.8633188740732
Length of Population = 20
Highest Current Fitness:
-70.8633188740732
Length of Population = 30
Highest Current Fitness:
-80.60137913362004
Length of Population = 20
Highest Current Fitness:
-73.09757716674072
Length of Population = 20
Highest Current Fitness:
-72.2824475872277
Length of Population = 20
Highest Current Fitness:
-71.23025729049294
Length of Population = 30
Highest Current Fitness:
-71.23025729049294
Length of Population = 40
Step: 1: current parameter_diff: 7.507502483151055, current data likelihood: 0.0
EM Iteration 2
E-step
M-step
Maximize Q-0
Highest Current Fitness:
-273.9272087107773
Lengt

### Estimeted Parameters

In [5]:
experiment_performance(result_dict=exper_dict, em=em)

Absolute diff in A:
[[0.38755054 0.        ]
 [1.2584057  0.        ]
 [0.         0.94971913]
 [0.23538561 1.37671964]
 [1.84441689 0.19020049]
 [0.         0.66609164]]
Absolute diff in delta:
[1.07881578 1.45478874 0.17426022 0.67262895 0.08410975 1.02928687]
Absolute diff in sigma:
[[0.         0.04484618]
 [0.04484618 0.        ]]


{'rmse_A': 0.8400514908057599,
 'rmse_delta': 0.8971766856114028,
 'rmse_sigma': 0.03171104151355746}

In [20]:
experiment_performance(result_dict=exper_dict, em=em)

Absolute diff in A:
[[0.08534941 0.        ]
 [0.89466606 0.        ]
 [0.         0.5462264 ]
 [0.3758118  0.11807726]
 [1.         0.1       ]
 [0.         0.5       ]]
Absolute diff in delta:
[1.10062348 1.98836146 1.72083674 1.56568859 0.64138087 0.32523404]
Absolute diff in sigma:
[[0.         0.22172733]
 [0.22172733 0.        ]]


{'rmse_A': 0.45837138346516654,
 'rmse_delta': 1.3598259561775639,
 'rmse_sigma': 0.15678489631601697}

In [6]:
em.model.item_parameters

{'discrimination_matrix': array([[0.41465059, 0.        ],
        [1.10533394, 0.        ],
        [0.        , 0.9462264 ],
        [0.3241882 , 0.71807726],
        [1.        , 1.        ],
        [0.        , 1.        ]]),
 'intercept_vector': array([1.10062348, 2.48836146, 2.72083674, 1.56568859, 0.85861913,
        0.57476596]),
 'q_matrix': array([[1, 0],
        [1, 0],
        [0, 1],
        [1, 1],
        [1, 1],
        [0, 1]])}